---
title: "STAT404_HW2_2017150431"
author: "CWY"
date: '2022-12-07'
output: pdf_document
---

# 1
## 4.7
### (a)
```{r}
N = 5000
sigma2 = 1 / rgamma(N, 10, 2.5); sigma = sqrt(sigma2)
theta = rnorm(N, 4.1, sqrt(sigma2 / 20))

newY = .31 * rnorm(N, theta, sigma) + .46 * rnorm(N, 2 * theta, 2 * sigma) +
  .23 * rnorm(N, 3 * theta, 3 * sigma)
hist(newY, freq = F)
```

### (b)
```{r}
quantile(newY, c(.125, .875))
```

\newpage

## 5.1
```{r}
school1 = scan('http://www2.stat.duke.edu/~pdh10/FCBS/Exercises/school1.dat')
school2 = scan('http://www2.stat.duke.edu/~pdh10/FCBS/Exercises/school2.dat')
school3 = scan('http://www2.stat.duke.edu/~pdh10/FCBS/Exercises/school3.dat')
mu0 = 5; sigma02 = 4; kappa0 = 1; nu0 = 2
```

### (a)
```{r}
n1 = length(school1); mean1 = mean(school1); var1 = var(school1)
n2 = length(school2); mean2 = mean(school2); var2 = var(school2)
n3 = length(school3); mean3 = mean(school3); var3 = var(school3)

post_mean1 = (n1 * mean1 + kappa0 * mu0) / (n1 + kappa0)
post_mean2 = (n2 * mean2 + kappa0 * mu0) / (n2 + kappa0)
post_mean3 = (n3 * mean3 + kappa0 * mu0) / (n3 + kappa0)

post_var1 = 1/(nu0 + n1) * (nu0 * sigma02 + (n1 - 1) * var1 + ((kappa0 * n1) / (kappa0 + n1)) * (mean1 - mu0)^2)
post_var2 = 1/(nu0 + n2) * (nu0 * sigma02 + (n2 - 1) * var2 + ((kappa0 * n2) / (kappa0 + n2)) * (mean2 - mu0)^2)
post_var3 = 1/(nu0 + n3) * (nu0 * sigma02 + (n3 - 1) * var3 + ((kappa0 * n3) / (kappa0 + n3)) * (mean3 - mu0)^2)

s.postsample1 = sqrt(1/rgamma(10000, (nu0 + n1)/2, post_var1 * (nu0 + n1)/2))
theta.postsample1 = rnorm(10000, post_mean1, s.postsample1/sqrt(kappa0 + n1))
cat("posterior mean for theta forschool1:", post_mean1)
cat("posterior mean for sd for school1:", sqrt(post_var1))
cat("95% CI for theta for school1:", quantile(theta.postsample1, probs = c(0.025, 0.975)))
cat("95% CI for sigma for school1:", quantile(s.postsample1, probs = c(0.025, 0.975)))

s.postsample2 = sqrt(1/rgamma(10000, (nu0 + n2)/2, post_var2 * (nu0 + n2)/2))
theta.postsample2 = rnorm(10000, post_mean2, s.postsample2/sqrt(kappa0 + n2))
cat("posterior mean for school2:", post_mean2)
cat("posterior mean for sd for school2:", sqrt(post_var2))
cat("95% CI for theta for school2:", quantile(theta.postsample2, probs = c(0.025, 0.975)))
cat("95% CI for sigma for school2:", quantile(s.postsample2, probs = c(0.025, 0.975)))

s.postsample3 = sqrt(1/rgamma(10000, (nu0 + n3)/2, post_var3 * (nu0 + n3)/2))
theta.postsample3 = rnorm(10000, post_mean3, s.postsample3/sqrt(kappa0 + n3))
cat("posterior mean for school3:", post_mean3)
cat("posterior mean for sd for school3:", sqrt(post_var3))
cat("95% CI for theta for school3:", quantile(theta.postsample3, probs = c(0.025, 0.975)))
cat("95% CI for sigma for school3:", quantile(s.postsample3, probs = c(0.025, 0.975)))
```


### (b)
```{r}
cat("permutation (1, 2, 3):", mean(theta.postsample1 < theta.postsample2 & theta.postsample2 < theta.postsample3))
cat("permutation (1, 3, 2):", mean(theta.postsample1 < theta.postsample3 & theta.postsample3 < theta.postsample2))
cat("permutation (2, 1, 3):", mean(theta.postsample2 < theta.postsample1 & theta.postsample1 < theta.postsample3))
cat("permutation (2, 3, 1):", mean(theta.postsample2 < theta.postsample3 & theta.postsample3 < theta.postsample1))
cat("permutation (3, 1, 2):", mean(theta.postsample3 < theta.postsample1 & theta.postsample1 < theta.postsample2))
cat("permutation (3, 2, 1):", mean(theta.postsample3 < theta.postsample2 & theta.postsample2 < theta.postsample1))
```


### (c)
```{r}
Y1 = rnorm(10000, theta.postsample1, s.postsample1)
Y2 = rnorm(10000, theta.postsample2, s.postsample1)
Y3 = rnorm(10000, theta.postsample3, s.postsample1)

cat("permutation (1, 2, 3):", mean(Y1 < Y2 & Y2 < Y3))
cat("permutation (1, 3, 2):", mean(Y1 < Y3 & Y3 < Y2))
cat("permutation (2, 1, 3):", mean(Y2 < Y1 & Y1 < Y3))
cat("permutation (2, 3, 1):", mean(Y2 < Y3 & Y3 < Y1))
cat("permutation (3, 1, 2):", mean(Y3 < Y1 & Y1 < Y2))
cat("permutation (3, 2, 1):", mean(Y3 < Y2 & Y2 < Y1))
```


### (d)
```{r}
cat("posterior probability that theta1 is bigger than both theta2 & theta3:", mean(theta.postsample1 > theta.postsample2 & theta.postsample1 > theta.postsample3))
cat("posterior probability that Y1 is bigger than both Y2 & Y3:", mean(Y1 > Y2 & Y1 > Y3))
```

\newpage

## 5.2
```{r}
set.seed(42)
n = 16; mu0 = 75; sd = 10; ybarA = 75.2; sdA = 7.3; ybarB = 77.5; sdB = 8.1
kappa = c(1, 2, 4, 8, 16, 32)
nu = c(1, 2, 4, 8, 16, 32)

post_meanA = vector(length = length(kappa)); post_varA = vector(length = length(kappa))
post_meanB = vector(length = length(kappa)); post_varB = vector(length = length(kappa))
prob = vector(length = length(kappa))

for (i in 1:length(kappa)){
  post_meanA[i] = (n * ybarA + kappa[i] * mu0) / (n + kappa[i])
  post_varA[i] = 1/(nu[i] + n) * (nu[i] * sd^2 + (n - 1) * sdA^2 + ((kappa[i] * n) / (kappa[i] + n)) * (ybarA - mu0)^2)
  post_meanB[i] = (n * ybarB + kappa[i] * mu0) / (n + kappa[i])
  post_varB[i] = 1/(nu[i] + n) * (nu[i] * sd^2 + (n - 1) * sdB^2 + ((kappa[i] * n) / (kappa[i] + n)) * (ybarB - mu0)^2)
}

for (i in 1:length(kappa)){
  s2.postsampleA = 1/rgamma(10000, (nu[i] + n)/2, post_varA[i] * (nu[i] + n)/2)
  theta.postsampleA = rnorm(10000, post_meanA[i], sqrt(s2.postsampleA[i]/(kappa[i] + n)))
  s2.postsampleB = 1/rgamma(10000, (nu[i] + n)/2, post_varB[i] * (nu[i] + n)/2)
  theta.postsampleB = rnorm(10000, post_meanB[i], sqrt(s2.postsampleB[i]/(kappa[i] + n)))
  prob[i] = mean(theta.postsampleA < theta.postsampleB)
  cat("for kappa, nu = ", i, ",",  i, "\n", "Probability of thetaA < thetaB is", mean(theta.postsampleA < theta.postsampleB), "\n")
}

plot(kappa, prob, type = "l")
```

As shown in the plot, although the probability of $\theta_A < \theta_B$ decreases as the values of $\kappa_0$ and $\nu_0$ increase, the probability of $\theta_A < \theta_B$ still stays above 0.5 by a certain amount. Therefore the plot can be the evidence that $\theta_A < \theta_B$.

\newpage

# 2

```{r}
n = 20; X = c(47, 64, 61, 61, 63, 61, 64, 66, 63, 67, 63.5, 65, 62, 64, 61, 56, 63, 65, 64, 59)
mu0 = 62; kappa0 = 1; tau02 = 1; alpha = 1; beta = 1; Xbar = mean(X); s2 = var(X)
```


## (a)

```{r}
S = 5000; PHI = matrix(nrow = S, ncol = 2)
phi = c(Xbar, 1/s2)
PHI[1, ] = phi

for (s in 2:S){
  mun = (mu0 / tau02 + n * Xbar * phi[2]) / (1/tau02 + n*phi[2])
  sig2n = 1/(1/tau02 + n * phi[2])
  phi[1] = rnorm(1, mun, sqrt(sig2n))
  
  alphan = alpha + n/2
  betan = beta + ((n - 1) * s2 + n * (Xbar - phi[1])^2)/2
  phi[2] = rgamma(1, alphan, betan)
  
  PHI[s,] = phi
}

head(PHI)
```

## (b)

```{r}
quantile(1/sqrt(PHI[, 2]), c(0.05, 0.95))
```

## (c)
```{r}
P90 = PHI[, 1] + 1.645/sqrt(PHI[, 2])
hist(P90, freq = F, breaks = 50)
lines(density(P90), col = "red")
```

## (d)
```{r}
mun = (mu0/tau02 + n * Xbar/s2) / (1/tau02 + n/s2)
taun = 1/(1/tau02 + n/s2)

S = 10^4
theta_pred = rnorm(S, mun, sqrt(taun))
Xpred = rnorm(S, theta_pred, sqrt(s2))

sd(Xpred)
```

\newpage 

# 3
## (b)

```{r}
a = 1; b = 1; lambda = 10; X = 7; S = 10^4

x = vector(length = S); theta = vector(length = S); n = vector(length = S);

x[1] = X
theta[1] = rbeta(1, a, b)
n[1] = rpois(1, lambda)

for (i in 2:(S + 1)){
  x[i] = rbinom(1, n[i - 1], theta[i - 1])
  theta[i] = rbeta(1, a + x[i], b + n[i - 1] - x[i])
  n[i] = x[i] + rpois(1, lambda * (1- theta[i]))
}

par(mfrow = c(1, 2))
hist(theta, freq = F, main = "Marginal posterior distributions of theta")
hist(n, freq = F, main = "Marginal posterior distributions of N")

summary(theta)
summary(n)
```
\newpage

# 4

## (a)
```{r}
n = 10; theta = log(33); x = c(14, 25, 45, 25, 30, 33, 19, 50, 34, 67)

like = 1
grid = seq(0.01, 5, 0.01)
for (i in 1:n){
  like = like * dnorm(log(x[i]), theta, sqrt(grid))
}

prior = 1/grid; prior = prior/sum(prior)
like = like/sum(like);  
post = prior * like; post = post/sum(post)
```

## (b)

```{r}
library(invgamma)

N = 10000

post_var = rinvgamma(N, n/2, sum((log(x) - theta)^2)/2)
den = density(post_var); den$y = den$y/sum(den$y)

plot(den, ylim = c(0, 0.05))
lines(grid, post, col = "red")
```

(a) and (b) seems to have similar distributions.

### (c)

```{r}
phi = pnorm(sqrt(post_var/2), 0, 1)
G = 2 * phi - 1
G = density(G); G$y = G$y/sum(G$y)
plot(G)
```